steps:
  - label: "build and test"
    commands:
      - "ln -s /usr/local/go/bin/go /usr/local/bin/go"
      - "ln -s /usr/local/go/bin/gofmt /usr/local/bin/gofmt"
      - echo "$(pwd)"
      - ls -al
      - "go mod tidy"
      - "go fmt ./..."
      - "git diff --quiet"
      - "go test ./..."
      - "go run ./smake/smake"
    plugins:
      - docker#v5.9.0:
          image: "golang:1.21.3-bookworm"
          shell: ["/bin/bash", "-elic"]
