steps:
  - label: "build and test"
    commands:
      - export PATH="/usr/local/go/bin:$PATH"
      - "go test ./..."
      - "go run ./smake/smake"
    plugins:
      - docker#v5.9.0:
          image: "golang:1.21.3-bookworm"
          shell: ["/bin/bash", "-elic"]
          propagate-uid-gid: true
