steps:
  - label: "build and test"
    commands:
      - "go test ./..."
      - "go run ./smake/smake"
    plugins:
      - docker#v5.9.0:
          image: "shanhu/bkgo"
          shell: ["/bin/bash", "-eic"]
          propagate-uid-gid: true
